### ISSUE TITLE
duplicate seqs

### ISSUE THREAD

**Issue by colindaven** [IOB-Muenster/MetaG#1]
hi, seems like one file contains dups:

samtools faidx ICTV_vmr.fa
[W::fai_insert_index] Ignoring duplicate sequence "KM272184" at byte offset 6279496
[W::fai_insert_index] Ignoring duplicate sequence "KP792690" at byte offset 7228843
[W::fai_insert_index] Ignoring duplicate sequence "KP010413" at byte offset 41973353

Cheers,
Colin

**Comment by IOB-Muenster** [comment]
Hi Colin,
Thank you for pointing this out. I analyzed this and found that the three IDs are indeed duplicates.
However, this is related to the ICTV VMR database (https://talk.ictvonline.org/taxonomy/vmr/m/vmr-file-repository/9341). For example, the GenBank ID KP010413 is listed as a reference sequence for Salmonella phage HB-2014 and Salmonella phage vB_SPuM_SP116. Thus, this issue should be addressed by ICTV.
However, we will have to fix this, as the IDs should be unique. Are you using fasta indexing for MetaG? This won't speed up the analysis in this program.
Best,
Felix

**Comment by colindaven** [comment]
Thanks Felix, I'm aware of that. I use faidx as a standard QC of any fasta I use.

Thanks for making the curated DBs available, I'm using them for a quick local blast analysis on our cluster. I may try your webtool at some stage as well (is there a limit I haven't seen yet to the limit and/or length, i.e. 1000bp + only, of nanopore sequences you can submit  ?)

Cheers,
Colin

**Comment by IOB-Muenster** [comment]
Hi Colin,
Using faidx as QC seems to be a good idea.
You are welcome! Currently, you are allowed to upload a file up to 6000 MB. You may also compress it as one of .tar, .gz, .zip or .bz2 in which case the size limit applies to the archive. MetaG is applicable to short and long reads. We don't have any length limit, so you may use anything from Illumina to Nanopore reads (fasta/fastq). By the way: There are standard parameters for short and long reads and each database.
I just fixed the issues with the duplicate headers. Please use the latest ICTV version: http://www.bioinformatics.uni-muenster.de/tools/metag/download/
The original version is still accessible from the "primary" subfolder on the download page.
Best,
Felix
